#!/bin/bash
read -p "Enter a number: " rows
for((i=rows; i>=1; i--))
do
  for((j=1; j<=i; j++))
  do
    echo -n "* "
  done
  echo
done
for((i=1; i<=rows-1; i++))
do
  for((j=1; j<=i+1; j++))
  do
    echo -n "* "
  done
  echo
done
